---
- hosts: localhost
  become: yes
  tasks:
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "/var/lib/jenkins/workspace/Docker_Package/ABC Technologies"
        name: docker.io/manikantarjy/abctechnologies
        push: true
        source: build
      register: build_output

    - debug:
        var: build_output

    - name: Start a container
      community.docker.docker_container:
        name: abc-application
        image: manikantarjy/abctechnologies
        state: started
        ports:
          - "1234:8081"
      register: container_output

    - debug:
        var: container_output

    - name: Create a Deployment by reading the definition from a local file
      command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml"
      register: kubectl_output

    - debug:
        var: kubectl_output
