- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "manikantarjy"
        password: "November@2k24"
        
    - name: Build an image and push it to a private repo
      community.docker.docker_image:
        build:
          path: "/var/lib/jenkins/workspace/Docker_Package/ABC Technologies"
        name: docker.io/manikantarjy/abctechnologies
        push: true
        source: build
      register: docker_build_output
      ignore_errors: yes  # Continue even if this fails for troubleshooting

    - debug:
        var: docker_build_output

    - name: Start the container
      community.docker.docker_container:
        name: abc-application
        image: manikantarjy/abctechnologies
        state: started
        ports:
          - "1234:8080"
      register: docker_container_output
      ignore_errors: yes

    - debug:
        var: docker_container_output

    - name: Deploy to Kubernetes
      command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/deployment.yml"
      register: kubernetes_output
      ignore_errors: yes

    - debug:
        var: kubernetes_output
